name: a Dev

on:
  push:
    paths:
      - ".github/workflows/a-*"
      - "packages/a/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test:
    name: Run Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          # これはnode_modulesをキャッシュしない
          # cache: 'npm'
          # cache-dependency-path: '**/package-lock.json'

      - name: Cache npm dir
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          # @see https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-contexts-to-create-cache-keys
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Setup root
        run: |
          npm ci --ignore-scripts

      - name: Run dev
        run: |
          cd packages/a
          npm run dev
